BASENAME=jquery.tapclick
BANNER='jQuery tapclick | http://github.com/cabin/jquery-tapclick | ©2013 Cabin'

.PHONY: release
release: $(BASENAME).min.js docs/index.html

%.js: %.coffee
	@echo // $(BANNER) >$@
	coffee --compile --bare --lint --print $< >>$@
	
# Using sed to strip the "generated by coffeescript" line, leaving the
# copyright line.
%.min.js: %.js
	uglifyjs <$< | sed 2d >$@

docs/index.html: $(BASENAME).coffee
	docco $< && mv docs/$(BASENAME).html $@
